pipeline {
    agent {
        docker {
            image 'maven:3.9.9-eclipse-temurin-17'   // Maven + Java 17 image
            args '-v /root/.m2:/root/.m2'          // Cache Maven dependencies
        }
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/SubhashPatibandla/CICD-Repository'
            }
        }

        stage('Build') {
            steps {
                sh 'mvn -f java-hellocicd-master/pom.xml clean package'
            }
        }

        stage('Archive') {
            steps {
                archiveArtifacts artifacts: 'java-hellocicd-master/target/*.jar', fingerprint: true
            }
        }

        stage('Test Reports') {
            steps {
                junit 'java-hellocicd-master/target/surefire-reports/*.xml'
            }
        }
    }
}
