pipeline {
    agent any

    tools {
        maven 'maven-3.6.3'
    }

    environment {
        SONARQUBE_SERVER = 'SonarQubeServer'
    }

    triggers {
        githubPush()
    }

    stages {
        stage('Checkout') {
            steps {
                git url: 'https://github.com/SubhashPatibandla/CICD-Repository.git', branch: 'main'
            }
        }
		stage('List Workspace') {
   			 steps {
        			bat 'dir'
    			}
		}

        stage('Build') {
            steps {
                bat 'cd "Day 5- CI Project for Beginners\\sample-app" && mvn clean package'
            }
        }
        stage('Store Artifacts') {
            steps {
                archiveArtifacts artifacts: 'target/*.jar', fingerprint: true
            }
        }

        stage('Publish JSON Results') {
            steps {
                script {
                    def result = [
                        buildNumber: env.BUILD_NUMBER,
                        status: currentBuild.currentResult,
                        timestamp: new Date().toString()
                    ]
                    writeJSON file: 'results/build-result.json', json: result
                    archiveArtifacts artifacts: 'results/build-result.json', fingerprint: true
                }
            }
        }
    }

    post {
        always {
            echo "Pipeline complete."
        }
    }
}
